### ISSUE TITLE
Long pooling example produce flooding into the chat

### ISSUE THREAD

**Issue by dimzon** [pathetic/tgbot-php#3]
'''
Дмитрий:
/echo 1
[3:18:15 PM] gemory123_bot:
Дмитрий says: 1

[3:18:20 PM] Дмитрий:
qdfasdfa
[3:18:19 PM] gemory123_bot:
Дмитрий says: 1

[3:18:23 PM] Дмитрий:
ewrewr
[3:18:23 PM] gemory123_bot:
Дмитрий says: 1
 Дмитрий says: 1

[3:18:28 PM] Дмитрий:
/echo 3
[3:18:32 PM] gemory123_bot:
Дмитрий says: 1
 Дмитрий says: 3
 Дмитрий says: 1
 Дмитрий says: 3
 Дмитрий says: 1
 Дмитрий says: 3
 Дмитрий says: 1
 Дмитрий says: 3
 Дмитрий says: 1
 Дмитрий says: 3
 Дмитрий says: 1
 Дмитрий says: 3
 Дмитрий says: 1
 Дмитрий says: 3
 Дмитрий says: 1
 Дмитрий says: 3
'''

**Comment by pathetic** [comment]
This package is no longer maintained.
